devsearch/urls.py
import imp
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

projects/urls.py
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
from projects.views import projects, project, create_project, update_project, delete_project


urlpatterns = [
    path('', projects, name='projects'),
    path('project/<str:pk>/', project, name='project'),
    path('create-project/', create_project, name='create-project'),
    path('update-project/<str:pk>/', update_project, name='update-project'),
    path('delete-project/<str:pk>/', delete_project, name='delete-project'),
]

users/urls.py
from django.urls import path
from users.views import profiles, user_profile

urlpatterns = [
    path('', profiles, name='profiles'),
    path('profile/<str:pk>', user_profile, name='user-profile'),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default='default.jpg')
    demo_link = models.CharField(max_length=2000,null=True, blank=True)
    source_link = models.CharField(max_length=2000,null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return self.title
    

class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    # owner
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=255, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return self.name      

users/models.py
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User
import uuid


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=255, null=True, blank=True)
    location = models.CharField(max_length=255, null=True, blank=True)
    short_intro = models.CharField(max_length=255, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=255, null=True, blank=True)
    social_twitter = models.CharField(max_length=255, null=True, blank=True)
    social_linkedin = models.CharField(max_length=255, null=True, blank=True)
    social_youtube = models.CharField(max_length=255, null=True, blank=True)
    social_website = models.CharField(max_length=255, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    
    def __str__(self) -> str:
        return str(self.user.username)


class Skill(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return self.name

projects/forms.py
from dataclasses import field
from django.forms import ModelForm
from projects.models import Project
from django import forms


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'featured_image', 'description', 'demo_link', 'source_link', 'tags']
        widgets = {
            'tags' : forms.CheckboxSelectMultiple(), 
        }

    def __init__(self, *args, **kwargs) -> None:
        super(ProjectForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class' : 'input'})

        # self.fields['title'].widget.attrs.update({'class' : 'input', 'placeholder' : 'Enter Title . . .'})

projects/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.http import HttpResponse
from projects.models import Project, Tag, Review
from projects.forms import ProjectForm

def projects(request):
    projects = Project.objects.all()
    context = {'projects' : projects }
    return render(request, 'projects/projects.html', context)


def project(request, pk):
    project_obj = Project.objects.get(id=pk)
    return render(request, 'projects/single-project.html', {'project' : project_obj}) 


def create_project(request):
    form = ProjectForm()

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projects')

    context = {'form' : form}
    return render(request, 'projects/project_form.html', context)


def update_project(request, pk):
    project = Project.objects.get(id=pk)
    form = ProjectForm(instance=project)

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('projects')

    context = {'form' : form}
    return render(request, 'projects/project_form.html', context)


def delete_project(request, pk):
    project = Project.objects.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('projects')

    context= {'project': project}

    return render(request, 'projects/delete_project.html', context)

users/views.py
from multiprocessing import context
from django.shortcuts import render
from users.models import Profile

def profiles(request):
    profile = Profile.objects.all()
    context = {
        'profiles' : profile
    }
    return render(request, 'users/profiles.html', context)


def user_profile(request, pk):
    user_profile = Profile.objects.get(id=pk)

    top_skills = user_profile.skill_set.exclude(description__exact="")
    other_skills = user_profile.skill_set.filter(description="")

    context = {
        'profile' : user_profile,
        'top_skills' : top_skills,
        'other_skills' : other_skills,
    }
    return render(request, 'users/user_profile.html', context)

projects/templates/projects/delete_project.html
{% extends 'main.html' %}

{% block content %}

    <form method="POST" action="">
        {% csrf_token %}
        <p>Are u Sure you want to delete "{{ project }}"</p>
        <a href="{% url 'projects' %}">
            Cancel
        </a>
        <input type="submit" value="Comfirm">
    </form>

{% endblock %}

projects/templates/projects/project_form.html
{% extends 'main.html' %}

{% block content %}

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'projects' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">{{ field.label }}</label>
                        {{field}}
                    </div>
                    {% endfor %}

                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>


{% endblock %}

projects/templates/projects/projects.html
{% extends 'main.html' %}
 {% block content %}
<body>
    

    <!-- Main Section -->
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>

    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">

            {% for project in projects %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'project' project.id %}" class="project">
                <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{project.title}}</h3>
                  <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">{{project.vote_ratio}}%</span> - 
                    Positive Feedback, Vote Total of ({{project.vote_total}})
                  </p>
                  <div class="project__tags">
                      {% for tag in project.tags.all %}
                    <span class="tag tag--pill tag--main">
                      <small>{{tag}}</small>
                    </span>
                    {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </section>
  </main>
</body>
{% endblock content %}

projects/templates/projects/single-project.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Tools & Stacks</h3>
          <div class="singleProject__toolStack">
              {% for tag in project.tags.all %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{tag}}</small>
            </span>
            {% endfor %}
          </div>
          {% if project.source_link %}
          <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i class="im im-external-link"></i>Source Code   
          </a>
          {% endif %}

          {% if project.demo_link %}
          <a class="singleProject__liveLink" href="{{ project.demo_link }}" target="_blank"><i class="im im-external-link"></i>Live Demo
          </a>
          {% endif %}
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{ project.featured_image.url }}" alt="portfolio thumbnail" />
          <a href="profile.html" class="singleProject__developer">By {{project.owner.name}}</a>
          <h2 class="singleProject__title">{{ project.title }}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            {{ project.description }}
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
                {{ project.vote_ratio }}% Postitive Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
            </h5>

            <form class="form" action="#" method="POST">
              <!-- Textarea -->
              <div class="form__field">
                <label for="formInput#textarea">Comments: </label>
                <textarea class="input input--textarea" name="message" id="formInput#textarea"
                  placeholder="Write your comments here..."></textarea>
              </div>
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form>
            <div class="commentList">
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md"
                    src="https://pbs.twimg.com/profile_images/1335382240931368961/b3wSZKj4_400x400.jpg" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Sulamita Ivanov</a>
                  <p class="comment__info">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit alias numquam perferendis
                    mollitia minus minima exercitationem possimus ab deserunt qui, soluta iusto doloribus eveniet
                    similique consequuntur ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Dennis Ivanov</a>
                  <p class="comment__info">
                    Consectetur adipisicing elit. Reprehenderit alias numquam perferendis mollitia minus minima
                    exercitationem possimus ab deserunt qui, ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>

{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<body>
  

  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Nodejs</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Express</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>GraphQL</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/1868782" alt="image" />
                  <div class="dev__meta">
                    <h3>Cody Seibert</h3>
                    <h5>React Developer, Coding Youtuber</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>Elixir</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>F#</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>.NET</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="image" />
                  <div class="dev__meta">
                    <h3>Dennis Ivy</h3>
                    <h5>Python & Django Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>Python</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Django</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Rest API</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div class="pagination">
      <ul class="container">
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        <li><a href="#" class="btn btn--sub">01</a></li>
        <li><a href="#" class="btn">02</a></li>
        <li><a href="#" class="btn">03</a></li>
        <li><a href="#" class="btn">04</a></li>
        <li><a href="#" class="btn">05</a></li>
        <li><a href="#" class="btn">06</a></li>
        <li><a href="#" class="btn">07</a></li>
        <li><a href="#" class="btn">08</a></li>
        <li><a href="#" class="btn">09</a></li>
        <li><a href="#" class="btn">10</a></li>
        <li><a href="#" class="btn">Next &#10095;</a></li>
      </ul>
    </div>
  </main>
</body>

</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      
        <!-- Favicon -->
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <!-- Icon - IconMonster -->
        <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
        <!-- Mumble UI -->
        <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
        <!-- Dev Search UI -->
        <link rel="stylesheet" href="{% static 'styles/app.css' %}" />
      
        <title>DevSearch - Connect with Developers!</title>
    </head>
    <body>
        {% include 'navbar.html' %}

        {% block content %}


        {% endblock content %}
    </body>
</html>

users/templates/users/user_profile.html
{% extends 'main.html' %}

{% block content %}

    <!-- Main Section -->
    <main class="profile my-md">
        <div class="container">
        <div class="layout">
            <div class="column column--1of3">
            <div class="card text-center">
                <div class="card__body dev">
                <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
                <h2 class="dev__name">{{profile.name}}</h2>
                <p class="dev__title">{{profile.short_intro}}</p>
                <p class="dev__location">Based in {{profile.location}}</p>
                <ul class="dev__social">
                    {% if profile.social_github %}
                    <li>
                    <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                    </li>
                    {% endif %}

                    {% if profile.social_youtube %}
                    <li>
                    <a title="Stackoverflow" href="#" target="_blank"><i class="im im-stackoverflow"></i></a>
                    </li>
                    {% endif %}

                    {% if profile.social_twitter %}
                    <li>
                    <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                    </li>
                    {% endif %}

                    {% if profile.social_linkedin %}
                    <li>
                    <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                    </li>
                    {% endif %}

                    {% if profile.social_website %}
                    <li>
                    <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                    </li>
                    {% endif %}

                </ul>
                <a href="#" class="btn btn--sub btn--lg">Send Message </a>
                </div>
            </div>
            </div>
            <div class="column column--2of3">
            <div class="devInfo">
                <h3 class="devInfo__title">About Me</h3>
                <p class="devInfo__about">
                {{profile.bio}}
                </p>
            </div>
            <div class="devInfo">
                <h3 class="devInfo__title">Skills</h3>
                <div class="devInfo__skills">
                {% for skill in top_skills %}
                <div class="devSkill">
                    <h4 class="devSkill__title">{{skill}}</h4>
                    <p class="devSkill__info">
                    {{skill.description}}
                    </p>
                </div>
                {% endfor %}
                <h3 class="devInfo__subtitle">Other Skills</h3>
                <div class="devInfo__otherSkills">
                    {% for skill in other_skills %}
                    <span class="tag tag--pill tag--sub tag--lg">
                    <small>{{skill}}</small>
                    {% endfor %}
                    
                </div>
                </div>
            </div>
            <div class="devInfo">
                <h3 class="devInfo__title">Projects</h3>
                <div class="grid grid--two">

                    {% for project in profile.project_set.all %}
                <div class="column">
                    <div class="card project">
                    <a href="{% url 'project' project.id %}" class="project">
                        <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                        <div class="card__body">
                        <h3 class="project__title">{{project.title}}</h3>
                        <p><a class="project__author" href="{% url 'user-profile' profile.id %}">By {{project.owner.name}}</a></p>
                        <p class="project--rating">
                            <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                            Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                        </p>
                        <div class="project__tags">
                            {% for tag in project.tags.all %}
                            <span class="tag tag--pill tag--main">
                            <small>{{tag}}</small>
                            </span>
                            {% endfor %}
                            
                        </div>
                        </div>
                    </a>
                    </div>
                </div>
                {% endfor %}

                </div>
            </div>
            </div>
        </div>
        </div>
    </main>

{% endblock content %}